capture:
  fps: 15
  fullscreen:
    height: 1440
    width: 3440
  mode: fullscreen
  roi:
    enabled: false
    h: 1440
    w: 3440
    x: 0
    y: 0
  window:
    fallback_to_fullscreen: true
    partial_match: true
    process_name: WorldOfTanks.exe
control:
  key_press_duration: 50
  mouse_sensitivity: 1.0
  safe_mode: true
debug:
  save_screenshots: false
  screenshot_interval: 100
  show_fps: true
  show_latency: true
logging:
  file_path: logs/client.log
  level: INFO
  save_to_file: true
network:
  adaptive_fps:
    enabled: false
    max_fps: 30
    min_fps: 10
    target_latency_ms: 50
  buffer_size: 8192
  compression: true
  jpeg_quality: 80
server:
  host: localhost
  port: 9999
  reconnect: true
  reconnect_interval: 5
  timeout: 10
