# PPO Configuration for World of Tanks AI

# Environment Settings
env:
  name: "WorldOfTanks-v0"
  frame_stack: 4
  frame_skip: 2
  max_episode_steps: 3000
  
  # Screen capture settings
  screen:
    width: 1920
    height: 1080
    roi:  # Region of interest (crop unnecessary UI)
      x: 0
      y: 0
      w: 1920
      h: 1080
    fps: 60
    
  # Action space
  actions:
    move: [-1.0, 0.0, 1.0]  # backward, stop, forward
    turn: [-1.0, -0.5, 0.0, 0.5, 1.0]  # left to right
    turret: [-1.0, -0.5, 0.0, 0.5, 1.0]
    shoot: [0, 1]  # don't shoot, shoot
    
  # Reward shaping
  rewards:
    damage_dealt: 1.0
    damage_received: -0.5
    kill: 10.0
    death: -20.0
    survival_bonus: 0.01  # per timestep
    spotted_enemy: 0.5
    assist_damage: 0.3

# PPO Hyperparameters
ppo:
  policy: "CnnPolicy"
  learning_rate: 3.0e-4
  n_steps: 2048
  batch_size: 64
  n_epochs: 10
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  clip_range_vf: null
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  use_sde: false
  sde_sample_freq: -1
  
# Network Architecture
network:
  # CNN feature extractor
  features_extractor:
    type: "NatureCNN"
    features_dim: 512
    
  # Policy network
  policy_net:
    hidden_sizes: [256, 256]
    activation: "relu"
    
  # Value network
  value_net:
    hidden_sizes: [256, 256]
    activation: "relu"

# Training Settings
training:
  total_timesteps: 10000000
  save_freq: 50000
  eval_freq: 10000
  eval_episodes: 10
  log_interval: 10
  
  # Checkpointing
  checkpoint_dir: "./models/checkpoints"
  best_model_dir: "./models/best"
  
  # Tensorboard
  tensorboard_log: "./logs/tensorboard"
  
  # Multi-GPU training
  device: "cuda"  # cuda, cpu
  n_envs: 1  # Parallel environments (requires multiple game instances)

# Curriculum Learning (optional)
curriculum:
  enabled: false
  stages:
    - name: "basic_movement"
      episodes: 1000
      rewards:
        damage_dealt: 0.1
        survival_bonus: 0.1
    - name: "combat_intro"
      episodes: 2000
      rewards:
        damage_dealt: 0.5
        survival_bonus: 0.05
    - name: "full_combat"
      episodes: -1  # unlimited
      rewards:
        damage_dealt: 1.0
        survival_bonus: 0.01

# Vision Module Settings
vision:
  # Tank detection
  detector:
    model: "yolov8n.pt"  # nano, small, medium, large, xlarge
    confidence_threshold: 0.4
    iou_threshold: 0.45
    device: "cuda"
    
  # Minimap analysis
  minimap:
    enabled: true
    location: [50, 50, 250, 250]  # x, y, w, h
    
# Debugging
debug:
  render: false
  save_replay: false
  verbose: 1
  log_level: "INFO"

